#!/usr/bin/env bash
# Run a signed openapi enclave on SGX hardware (Fortanix ftxsgx-runner).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT}"

TARGET="x86_64-fortanix-unknown-sgx"
PROFILE="${SGX_PROFILE:-release}"
SIGNED="${OPENAPI_SGX_ENCLAVE:-${ROOT}/target/${TARGET}/${PROFILE}/openapi-enclave.sgxs}"

if [[ ! -f "${SIGNED}" ]]; then
  echo "SGXS enclave not found: ${SIGNED}" >&2
  echo "Run: ./deploy/sgx/build-enclave.sh" >&2
  exit 1
fi

SIG_CORESIDENT="${SIGNED%.sgxs}.sig"
if [[ ! -f "${SIG_CORESIDENT}" ]]; then
  echo "Coresident signature missing: ${SIG_CORESIDENT}" >&2
  echo "Run: ./deploy/sgx/build-enclave.sh" >&2
  exit 1
fi

: "${OPENAPI_MRENCLAVE:?Set OPENAPI_MRENCLAVE from sgxs-info summary output}"
: "${OPENAPI_PROFILE:?Set OPENAPI_PROFILE explicitly to dev or prod}"
: "${OPENAPI_UPSTREAM_BASE_URL:?Set OPENAPI_UPSTREAM_BASE_URL (http://IP:port — no DNS)}"
: "${OPENAPI_CATALOG_VERIFY_KEY_HEX:?Set OPENAPI_CATALOG_VERIFY_KEY_HEX}"
: "${OPENAPI_USAGE_SIGN_SEED_HEX:?Set OPENAPI_USAGE_SIGN_SEED_HEX}"
export OPENAPI_AUTH_MODE="${OPENAPI_AUTH_MODE:-remote}"
if [[ "${OPENAPI_AUTH_MODE}" == "catalog" ]]; then
  : "${OPENAPI_CATALOG_JSON:?Set OPENAPI_CATALOG_JSON for catalog auth (inline; EDP has no host fs)}"
fi

export OPENAPI_LISTEN_ADDR="${OPENAPI_LISTEN_ADDR:-0.0.0.0:8443}"
export RUST_LOG="${RUST_LOG:-info}"

echo "Running enclave ${SIGNED} (sig ${SIG_CORESIDENT})"
echo "Listen: ${OPENAPI_LISTEN_ADDR}  MRENCLAVE: ${OPENAPI_MRENCLAVE}  AUTH: ${OPENAPI_AUTH_MODE}"

# Fortanix EDP: empty host env inside enclave — pass KEY=VALUE as enclave args.
ARGS=(
  "OPENAPI_MRENCLAVE=${OPENAPI_MRENCLAVE}"
  "OPENAPI_UPSTREAM_BASE_URL=${OPENAPI_UPSTREAM_BASE_URL}"
  "OPENAPI_CATALOG_VERIFY_KEY_HEX=${OPENAPI_CATALOG_VERIFY_KEY_HEX}"
  "OPENAPI_USAGE_SIGN_SEED_HEX=${OPENAPI_USAGE_SIGN_SEED_HEX}"
  "OPENAPI_LISTEN_ADDR=${OPENAPI_LISTEN_ADDR}"
  "OPENAPI_BUILD_VERSION=${OPENAPI_BUILD_VERSION:-sgx}"
)
[[ -n "${OPENAPI_CATALOG_JSON:-}" ]] && ARGS+=("OPENAPI_CATALOG_JSON=${OPENAPI_CATALOG_JSON}")
# Prod profile policy requires these env names set; EDP loads bytes via ceremony helper.
if [[ -n "${OPENAPI_CEREMONY_HELPER_URL:-}" ]]; then
  : "${OPENAPI_TLS_CERT_PATH:=helper://tls.crt}"
  : "${OPENAPI_TLS_SEALED_KEY_PATH:=helper://sealed-key.json}"
fi
[[ -n "${OPENAPI_TLS_CERT_PATH:-}" ]] && ARGS+=("OPENAPI_TLS_CERT_PATH=${OPENAPI_TLS_CERT_PATH}")
[[ -n "${OPENAPI_TLS_SEALED_KEY_PATH:-}" ]] && ARGS+=("OPENAPI_TLS_SEALED_KEY_PATH=${OPENAPI_TLS_SEALED_KEY_PATH}")
[[ -n "${OPENAPI_DCAP_HELPER_URL:-}" ]] && ARGS+=("OPENAPI_DCAP_HELPER_URL=${OPENAPI_DCAP_HELPER_URL}")
[[ -n "${OPENAPI_CEREMONY_HELPER_URL:-}" ]] && ARGS+=("OPENAPI_CEREMONY_HELPER_URL=${OPENAPI_CEREMONY_HELPER_URL}")
ARGS+=("OPENAPI_PROFILE=${OPENAPI_PROFILE}")
[[ -n "${OPENAPI_AUTH_MODE:-}" ]] && ARGS+=("OPENAPI_AUTH_MODE=${OPENAPI_AUTH_MODE}")
[[ -n "${OPENAPI_L0_AUTHORIZE_URL:-}" ]] && ARGS+=("OPENAPI_L0_AUTHORIZE_URL=${OPENAPI_L0_AUTHORIZE_URL}")
[[ -n "${OPENAPI_L0_REVOCATIONS_URL:-}" ]] && ARGS+=("OPENAPI_L0_REVOCATIONS_URL=${OPENAPI_L0_REVOCATIONS_URL}")
[[ -n "${OPENAPI_L0_INTERNAL_TOKEN:-}" ]] && ARGS+=("OPENAPI_L0_INTERNAL_TOKEN=${OPENAPI_L0_INTERNAL_TOKEN}")
# F′ OPE dispatch (topology B′) — inline PEMs only on EDP.
[[ -n "${OPENAPI_GATEWAY_OPE_API_URL:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_URL=${OPENAPI_GATEWAY_OPE_API_URL}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_TOKEN:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_TOKEN=${OPENAPI_GATEWAY_OPE_API_TOKEN}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_TLS_CA_PEM:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_TLS_CA_PEM=${OPENAPI_GATEWAY_OPE_API_TLS_CA_PEM}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_CERT_PEM:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_CERT_PEM=${OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_CERT_PEM}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_KEY_PEM:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_KEY_PEM=${OPENAPI_GATEWAY_OPE_API_TLS_CLIENT_KEY_PEM}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_TLS_INSECURE_SKIP_VERIFY:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_TLS_INSECURE_SKIP_VERIFY=${OPENAPI_GATEWAY_OPE_API_TLS_INSECURE_SKIP_VERIFY}")
[[ -n "${OPENAPI_GATEWAY_OPE_API_READ_TIMEOUT_SECS:-}" ]] && ARGS+=("OPENAPI_GATEWAY_OPE_API_READ_TIMEOUT_SECS=${OPENAPI_GATEWAY_OPE_API_READ_TIMEOUT_SECS}")
[[ -n "${OPENAPI_ENGINE_IDENTITY_PINS_JSON:-}" ]] && ARGS+=("OPENAPI_ENGINE_IDENTITY_PINS_JSON=${OPENAPI_ENGINE_IDENTITY_PINS_JSON}")
[[ -n "${OPENAPI_OPE_EPOCH_CLOCK_SKEW_SEC:-}" ]] && ARGS+=("OPENAPI_OPE_EPOCH_CLOCK_SKEW_SEC=${OPENAPI_OPE_EPOCH_CLOCK_SKEW_SEC}")
[[ -n "${OPENAPI_UPSTREAM_CLEAR_HTTP:-}" ]] && ARGS+=("OPENAPI_UPSTREAM_CLEAR_HTTP=${OPENAPI_UPSTREAM_CLEAR_HTTP}")
[[ -n "${RUST_LOG:-}" ]] && ARGS+=("RUST_LOG=${RUST_LOG}")
# Challenge rate limits (0 = unlimited for bench). Fortanix does not inherit host env.
[[ -n "${OPENAPI_CHALLENGE_RPM:-}" ]] && ARGS+=("OPENAPI_CHALLENGE_RPM=${OPENAPI_CHALLENGE_RPM}")
[[ -n "${OPENAPI_CHALLENGE_MAX_INFLIGHT:-}" ]] && ARGS+=("OPENAPI_CHALLENGE_MAX_INFLIGHT=${OPENAPI_CHALLENGE_MAX_INFLIGHT}")
[[ -n "${OPENAPI_CHALLENGE_BENCH_TOKEN:-}" ]] && ARGS+=("OPENAPI_CHALLENGE_BENCH_TOKEN=${OPENAPI_CHALLENGE_BENCH_TOKEN}")
# Ceremony / seal-sync practice slots (CVM parity).
[[ -n "${OPENAPI_ARTIFACT_SLOT:-}" ]] && ARGS+=("OPENAPI_ARTIFACT_SLOT=${OPENAPI_ARTIFACT_SLOT}")
[[ -n "${OPENAPI_TLS_KEY_POLICY:-}" ]] && ARGS+=("OPENAPI_TLS_KEY_POLICY=${OPENAPI_TLS_KEY_POLICY}")
[[ -n "${OPENAPI_SEAL_SYNC_LISTEN:-}" ]] && ARGS+=("OPENAPI_SEAL_SYNC_LISTEN=${OPENAPI_SEAL_SYNC_LISTEN}")
[[ -n "${OPENAPI_SEAL_SYNC_PEER:-}" ]] && ARGS+=("OPENAPI_SEAL_SYNC_PEER=${OPENAPI_SEAL_SYNC_PEER}")
[[ -n "${OPENAPI_SEAL_SYNC_ALLOWLIST:-}" ]] && ARGS+=("OPENAPI_SEAL_SYNC_ALLOWLIST=${OPENAPI_SEAL_SYNC_ALLOWLIST}")
[[ -n "${OPENAPI_SEAL_SYNC_PSK:-}" ]] && ARGS+=("OPENAPI_SEAL_SYNC_PSK=${OPENAPI_SEAL_SYNC_PSK}")
[[ -n "${OPENAPI_SEAL_SYNC_CHALLENGE_BASE_URL:-}" ]] && ARGS+=("OPENAPI_SEAL_SYNC_CHALLENGE_BASE_URL=${OPENAPI_SEAL_SYNC_CHALLENGE_BASE_URL}")
[[ -n "${OPENAPI_MODE:-}" ]] && ARGS+=("OPENAPI_MODE=${OPENAPI_MODE}")
[[ -n "${OPENAPI_ACME_DOMAIN:-}" ]] && ARGS+=("OPENAPI_ACME_DOMAIN=${OPENAPI_ACME_DOMAIN}")
[[ -n "${OPENAPI_ACME_EMAIL:-}" ]] && ARGS+=("OPENAPI_ACME_EMAIL=${OPENAPI_ACME_EMAIL}")
[[ -n "${OPENAPI_ACME_STAGING:-}" ]] && ARGS+=("OPENAPI_ACME_STAGING=${OPENAPI_ACME_STAGING}")
[[ -n "${OPENAPI_ACME_CERT_NAME:-}" ]] && ARGS+=("OPENAPI_ACME_CERT_NAME=${OPENAPI_ACME_CERT_NAME}")
# Extra positional modes (acme-issue / acme-renew) after KEY=VALUE args.
EXTRA_POS=()
[[ -n "${OPENAPI_ENCLAVE_MODE_ARG:-}" ]] && EXTRA_POS+=("${OPENAPI_ENCLAVE_MODE_ARG}")

# Default DCAP helper for ECDSA quotes (host openapi-dcap-helper).
if [[ -z "${OPENAPI_DCAP_HELPER_URL:-}" ]]; then
  ARGS+=("OPENAPI_DCAP_HELPER_URL=http://127.0.0.1:18500")
fi

# Ceremony helper (TLS artifacts) — required for sealed TLS on EDP (no std::fs).
# Set OPENAPI_CEREMONY_HELPER_URL=http://127.0.0.1:18501 after issue-and-seal-tls.sh.
# When unset, edge may run plain TCP (lab) or fail clearly if sealed paths need FS.

exec ftxsgx-runner --signature coresident "${SIGNED}" "${ARGS[@]}" "${EXTRA_POS[@]}"
